### ISSUE TITLE
I cant compile for android  #include <boost/operators.hpp> 

### ISSUE THREAD

**Issue by HERRKIN** [rodgomesc/vision-camera-qrcode-scanner#96]
Hello, I am so confused with this module, I try to compile it and it throws this error the first time:

`error ../../node_modules/mobx-react-lite/src/utils/reactionCleanupTrackingCommon.ts: Unexpected token: name (_000) in file ../../node_modules/mobx-react-lite/src/utils/reactionCleanupTrackingCommon.ts at 18:48.
Error: Unexpected token: name (_000) in file ../../node_modules/mobx-react-lite/src/utils/reactionCleanupTrackingCommon.ts at 18:48
    at minifyCode (/Users/herrkin/dev/keplr-wallet/obi-wallet/node_modules/metro-config/node_modules/metro-transform-worker/src/index.js:101:13)
    at transformJS (/Users/herrkin/dev/keplr-wallet/obi-wallet/node_modules/metro-config/node_modules/metro-transform-worker/src/index.js:319:28)
    at transformJSWithBabel (/Users/herrkin/dev/keplr-wallet/obi-wallet/node_modules/metro-config/node_modules/metro-transform-worker/src/index.js:410:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/herrkin/dev/keplr-wallet/obi-wallet/node_modules/metro-config/node_modules/metro-transform-worker/src/index.js:571:12)
info Run CLI with --verbose flag for more details.`

then if I try again it will throw errors saying it can't find boost/operators.hpp, I looked at the folder and yeah it isnt there, the only file for boost is the one the module downloads but it throws the error.

**Comment by Productivix** [comment]
hi, we can help but with more infos !
it works with last RN 0.70.0 version , very good job @rodgomesc ! 
`
"dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.0",
    "react-native-reanimated": "^2.10.0",
    "react-native-vision-camera": "^2.14.1",
    "vision-camera-code-scanner": "^0.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-test-renderer": "18.1.0"
  },
`

**Comment by CodingWithNobody** [comment]
Try this https://www.youtube.com/watch?v=sE0MEyFA7E4&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=7 & https://www.youtube.com/watch?v=BFkIIIKgjnE&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=80
